# Generated by Django 3.0.10 on 2020-10-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20201014_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
